- name: configuring roboshop frontend
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: insall nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete the default html dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      status: absent
  
  - name: create html dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      status: present
  
  - name: downlaod the frontend contents
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
  
  - name: extract the contents
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: proxy configuration - remove the nginx.conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      status: absent
  
  - name: proxy configuration - copy the conf file from local
    ansible.builtin.copy: 
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted