- name: install mongodb
  become: yes
  hosts: mongodb
  tasks:
  - name: create an entry for repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-org 
      state: present
  
  - name: enable and start mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  # - name: enable and start mongodb
  #   ansible.builtin.service:
  #     name: mongodb-org
  #     state: started

  - name: allow remote connetions
    ansible.builtin.replace:
      regexp: '127.0.0.0'
      replace: '0.0.0.0'

  - name: start mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted