- name: Payment configuration for RoboShop
  become: yes
  hosts: payment 
  tasks:
  - name: install python3
    ansible.builtin.command: dnf install python3 gcc python3-devel -y

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true
  
  - name: make /app dir
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip
  
  - name: unzip the application 
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: true
  
  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy paymet.service
    ansilbe.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: enable and start payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes
  
