- name: rabbitmq configuration
  become: yes
  hosts: rabbitmq
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq-server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
  
  - name: start and enable rabbitmq service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Update RabbitMQ user password
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhosts: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present
      
