- name: configure shipping for roboshop
  become: yes
  hosts: shipping
  tasks:
    - name: install maven
      ansbile.builtin.dnf:
        name: maven
        state: present
    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: true
    
    - name: create app dir
      ansible.builtin.file:
       path: /app
       state: directory

    - name: download application code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unzip the application code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
    - name: setup new service in systemd - copy the configuation file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon_reload
      ansible.systemd_service:
        daemon_reload: yes
    
    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes
    
    - name: installing mysql
      ansible.builtin.dnf:
        name: mysql
        state: present
    
    - name: load schema data into mysql
      ansible.builtin.shell: mysql -h mysql.singireddy.shop -uroot -pRoboShop@1 < /app/db/schema.sql

    - name: create app user - in mysql database for shipping app to connect
      ansilble.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/app-user.sql

    - name: load master data
      ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/master-data.sql

    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes

