- name: user configuration
  hosts: user
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y 
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app 
      system: true 

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip #since the soruce dir is on the remote server, i.e not on where the script is run
      dest: /app
      remote_src: yes #remote_src is used when the file already exits on remote server

  - name: install dependencies 
    ansible.community.general.npm:
     path: /app

  - name: configuring systemd - Copying user service to remote
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: yes

  - name: starting and enabling user service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes